<a href="https://colab.research.google.com/github/lochan613/informal-credit-risk-engine/blob/main/ProjectML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import numpy as np

In [ ]:
household= pd.read_csv("/content/hhv1.csv")
household

,FI_hhv1,B1q2_hhv1,qtr_hhv1,visit_hhv1,b1q3_hhv1,state_hhv1,distcode_hhv1,nss_region_hhv1,b1q5_hhv1,b1q6_hhv1,...,b3q5pt4_hhv1,b3q5pt5_hhv1,b3q5pt6_hhv1,b1q16_hhv1,b2q2i_hhv1,b2q4_hhv1,nss_hhv1,nsc_hhv1,mult_hhv1,no_qtr_hhv1
0,FVH7,104,Q1,V1,1,2,4,21,1,14,...,10000,0,8733,3,11082023,70,2,4,246798,4
1,FVH7,104,Q1,V1,1,2,4,21,1,14,...,9000,0,7550,3,11082023,60,2,4,35596,4
2,FVH7,104,Q1,V1,1,2,4,21,1,14,...,10000,0,8483,1,11082023,64,2,4,35596,4
3,FVH7,104,Q1,V1,1,2,4,21,1,14,...,8000,0,7017,1,10082023,65,2,4,61700,4
4,FVH7,104,Q1,V1,1,2,4,21,1,14,...,8000,5000,9333,3,10082023,65,2,4,1613680,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101915,FVH7,104,Q4,V1,2,28,3,281,4,4,...,6500,0,14042,1,28052024,35,3,6,1935507,4
101916,FVH7,104,Q4,V1,2,28,3,281,4,4,...,10000,31500,16958,1,28052024,30,3,6,733146,4
101917,FVH7,104,Q4,V1,2,28,3,281,4,4,...,8500,0,14708,1,28052024,30,3,6,733146,4
101918,FVH7,104,Q4,V1,2,28,3,281,4,4,...,5800,21500,14525,1,31052024,30,3,6,469214,4
101919,FVH7,104,Q4,V1,2,28,3,281,4,4,...,20000,0,21667,1,28052024,40,3,6,469214,4

In [ ]:
len(household.columns)

37

In [ ]:
household.dtypes

FI_hhv1             object
B1q2_hhv1            int64
qtr_hhv1            object
visit_hhv1          object
b1q3_hhv1            int64
state_hhv1           int64
distcode_hhv1        int64
nss_region_hhv1      int64
b1q5_hhv1            int64
b1q6_hhv1            int64
b1q11_hhv1           int64
b1q12_hhv1           int64
b1q1_hhv1            int64
b1q13_hhv1           int64
b1q14_hhv1           int64
b1q15_hhv1           int64
b1q9_hhv1            int64
b1q17_hhv1           int64
b1q18_hhv1           int64
b1q19_hhv1         float64
b3q1_hhv1            int64
b3q2_hhv1            int64
b3q3_hhv1            int64
b3q4_hhv1            int64
b3q5pt1_hhv1         int64
b3q5pt2_hhv1         int64
b3q5pt3_hhv1         int64
b3q5pt4_hhv1         int64
b3q5pt5_hhv1         int64
b3q5pt6_hhv1         int64
b1q16_hhv1           int64
b2q2i_hhv1           int64
b2q4_hhv1            int64
nss_hhv1             int64
nsc_hhv1             int64
mult_hhv1            int64
no_qtr_hhv1          int64
dtype: object

In [ ]:
household_revisit = pd.read_csv("/content/hhrv.csv")
household_revisit

,FI_hhrv,B1q2_hhrv,qtr_hhrv,visit_hhrv,b1q3_hhrv,state_hhrv,distcode_hhrv,nss_region_hhrv,b1q5_hhrv,b1q6_hhrv,...,b3q3_hhrv,b3q4_hhrv,b3q5_hhrv,b1q16_hhrv,b2q2i_hhrv,b2q4_hhrv,nss_hhrv,nsc_hhrv,mult_hhrv,no_qtr_hhrv
0,RVH7,104,Q1,V2,2,28,3,281,4,4,...,1,3,17100,1,9072023,10,3,6,1134607,4
1,RVH7,104,Q1,V2,2,28,3,281,4,4,...,1,9,16475,1,9072023,11,3,6,1134607,4
2,RVH7,104,Q1,V2,2,28,3,281,4,4,...,1,3,7980,1,9072023,12,3,6,1601799,4
3,RVH7,104,Q1,V2,2,28,3,281,4,4,...,1,9,9517,1,9072023,14,3,6,1601799,4
4,RVH7,104,Q1,V2,2,28,3,281,4,4,...,1,3,6833,1,9072023,10,3,6,1735282,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132839,RVH7,104,Q4,V4,2,24,7,242,4,4,...,1,2,21750,1,5042024,45,6,12,2224761,4
132840,RVH7,104,Q4,V4,2,24,7,242,4,4,...,1,2,11250,1,5042024,35,6,12,3729746,4
132841,RVH7,104,Q4,V4,2,24,7,242,4,4,...,1,2,15833,2,5042024,40,6,12,3729746,4
132842,RVH7,104,Q4,V4,2,24,7,242,4,4,...,1,2,8917,1,5042024,25,6,12,3598878,4
132843,RVH7,104,Q4,V4,2,24,7,242,4,4,...,1,2,13417,2,5042024,35,6,12,3598878,4

In [ ]:
len(household_revisit.columns)

32

In [ ]:
household_revisit.dtypes

FI_hhrv             object
B1q2_hhrv            int64
qtr_hhrv            object
visit_hhrv          object
b1q3_hhrv            int64
state_hhrv           int64
distcode_hhrv        int64
nss_region_hhrv      int64
b1q5_hhrv            int64
b1q6_hhrv            int64
b1q11_hhrv           int64
b1q12_hhrv           int64
b1q1_hhrv            int64
b1q13_hhrv           int64
b1q14_hhrv           int64
b1q15_hhrv           int64
b1q9_hhrv            int64
b1q17_hhrv           int64
b1q18_hhrv           int64
b1q19_hhrv         float64
b3q1_hhrv            int64
b3q2_hhrv            int64
b3q3_hhrv            int64
b3q4_hhrv            int64
b3q5_hhrv            int64
b1q16_hhrv           int64
b2q2i_hhrv           int64
b2q4_hhrv            int64
nss_hhrv             int64
nsc_hhrv             int64
mult_hhrv            int64
no_qtr_hhrv          int64
dtype: object

In [ ]:
personlevel = pd.read_csv("/content/perv1.csv")
personlevel

,FI_perv1,B1q2_perv1,qtr_perv1,visit_perv1,b1q3_perv1,state_perv1,distcode_perv1,nss_region_perv1,b1q5_perv1,b1q6_perv1,...,b6q8_3pt7_perv1,b6q5_perv1,b6q6_perv1,b6q7_perv1,b6q9_perv1,b6q10_perv1,NSS_perv1,NSC_perv1,mult_perv1,no_qtr_perv1
0,FVP7,104,Q1,V1,1,2,4,21,1,14,...,0,94,NaN,NaN,0,0,2,4,246798,4
1,FVP7,104,Q1,V1,1,2,4,21,1,14,...,0,93,NaN,NaN,0,0,2,4,246798,4
2,FVP7,104,Q1,V1,1,2,4,21,1,14,...,0,11,1.0,611.0,0,6500,2,4,246798,4
3,FVP7,104,Q1,V1,1,2,4,21,1,14,...,3,21,1.0,611.0,0,0,2,4,246798,4
4,FVP7,104,Q1,V1,1,2,4,21,1,14,...,0,91,NaN,NaN,0,0,2,4,246798,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
418154,FVP7,104,Q4,V1,2,28,3,281,4,4,...,0,11,69.0,261.0,0,25000,3,6,733146,4
418155,FVP7,104,Q4,V1,2,28,3,281,4,4,...,0,94,NaN,NaN,0,0,3,6,733146,4
418156,FVP7,104,Q4,V1,2,28,3,281,4,4,...,0,94,NaN,NaN,0,0,3,6,469214,4
418157,FVP7,104,Q4,V1,2,28,3,281,4,4,...,0,31,49.0,313.0,52500,0,3,6,469214,4
418158,FVP7,104,Q4,V1,2,28,3,281,4,4,...,0,31,85.0,233.0,25000,0,3,6,469214,4

In [ ]:
len(personlevel.columns)
personlevel.columns

Index(['FI_perv1', 'B1q2_perv1', 'qtr_perv1', 'visit_perv1', 'b1q3_perv1',
       'state_perv1', 'distcode_perv1', 'nss_region_perv1', 'b1q5_perv1',
       'b1q6_perv1',
       ...
       'b6q8_3pt7_perv1', 'b6q5_perv1', 'b6q6_perv1', 'b6q7_perv1',
       'b6q9_perv1', 'b6q10_perv1', 'NSS_perv1', 'NSC_perv1', 'mult_perv1',
       'no_qtr_perv1'],
      dtype='object', length=139)

In [ ]:
NotNullPersonlevel = pd.notnull(personlevel)
NotNullpersonlevel1 = personlevel[NotNullPersonlevel[['b5q11', 'b5q12_perv1', 'b5q13_perv1']]]
display(NotNullpersonlevel1)

KeyError: "None of [Index(['b5q11', 'b5q12_perv1', 'b5q13_perv1'], dtype='object')] are in the [columns]"

In [ ]:
personlevel_revisit = pd.read_csv("/content/perrv.csv")
personlevel_revisit

,FI_perrv,B1q2_perrv,qtr_perrv,visit_perrv,b1q3_perrv,state_perrv,dist_code_perrv,nss_region_perrv,b1q5_perrv,b1q6_perrv,...,b6q8_3pt7_perrv,b6q5_perrv,b6q6_perrv,b6q7_perrv,b6q9_perrv,b6q10_perrv,NSS_perrv,NSC_perrv,mult_perrv,no_qtr_perrv
0,RVP7,104,Q1,V2,2,28,3,281,4,4,...,0,31,25.0,721.0,20000,0,3,6,1134607,4
1,RVP7,104,Q1,V2,2,28,3,281,4,4,...,0,92,NaN,NaN,0,0,3,6,1134607,4
2,RVP7,104,Q1,V2,2,28,3,281,4,4,...,0,91,NaN,NaN,0,0,3,6,1134607,4
3,RVP7,104,Q1,V2,2,28,3,281,4,4,...,0,91,NaN,NaN,0,0,3,6,1134607,4
4,RVP7,104,Q1,V2,2,28,3,281,4,4,...,0,31,85.0,233.0,58700,0,3,6,1134607,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
504435,RVP7,104,Q4,V4,2,24,7,242,4,4,...,0,94,NaN,NaN,0,0,6,12,3598878,4
504436,RVP7,104,Q4,V4,2,24,7,242,4,4,...,0,31,97.0,911.0,5000,0,6,12,3598878,4
504437,RVP7,104,Q4,V4,2,24,7,242,4,4,...,0,95,NaN,NaN,0,0,6,12,3598878,4
504438,RVP7,104,Q4,V4,2,24,7,242,4,4,...,0,31,47.0,524.0,10000,0,6,12,3598878,4
504439,RVP7,104,Q4,V4,2,24,7,242,4,4,...,0,31,86.0,911.0,8000,0,6,12,3598878,4

In [ ]:
len(personlevel_revisit.columns)

104